env = Environment()
env.Append(CCFLAGS='-g')

common = ["ShareMemoryLib.c"]
simHostFiles = ["SimHost.c"] + common
simDeviceFiles = ["SimDevice.c"] + common

env.Program('exe/CPU0.exe', simHostFiles)
env.Program('exe/CPU1.exe', simDeviceFiles)
env.Program('exe/CPU2.exe', simHostFiles)
env.Program('exe/CPU3.exe', simDeviceFiles)
