env = Environment()
env.Append(CCFLAGS='-g')

common = ["ShareMemoryLib.c"]
simHostFiles = ["SimHost.c"] + common
simDeviceFiles = ["SimDevice.c"] + common
env.Program('exe/SimHost.exe', simHostFiles)
env.Program('exe/SimDevice.exe', simDeviceFiles)
